name: wimbli
description: "Discover spontaneousevents events happening around you."
publish_to: "none"
version: 1.8.4+96

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  shared_preferences: ^2.2.3
  cloud_firestore: ^5.1.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  geolocator: ^12.0.0
  geolocator_android: 4.6.1
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  firebase_messaging: ^15.0.1
  permission_handler: ^11.3.1
  cloud_functions: ^5.0.1
  app_links: ^3.4.1
  device_calendar: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/wimbliLogoWhite.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/wimbliLogoWhite.png
